// src/lib/components/ProjectAchievements.svelte
<script lang="ts">
  import { getContext, untrack } from 'svelte';
  import { slide } from 'svelte/transition';
  import { ChevronDown } from 'lucide-svelte';

  import Badge from '$lib/components/Badge.svelte';
  import { sanitizeProjectHtml } from '$lib/utils/safeHtml';

  export interface Achievement {
    tag: string;
    accent?: boolean;
    title: string;
    detail: string;
  }

  interface Props {
    achievements: Achievement[];
  }

  let { achievements }: Props = $props();

  const isPrintMode = getContext<boolean | undefined>('printMode') ?? false;

  const firstAccentIndex = $derived(achievements.findIndex((a) => a.accent));
  const sanitizedAchievements = $derived(
    achievements.map((achievement) => ({
      ...achievement,
      detail: sanitizeProjectHtml(achievement.detail),
    })),
  );

  let openIndex = $state(untrack(() => (firstAccentIndex >= 0 ? firstAccentIndex : 0)));

  function toggle(index: number): void {
    openIndex = openIndex === index ? -1 : index;
  }
</script>

<div class="achievements">
  {#each sanitizedAchievements as achievement, i (i)}
    {@const isOpen = openIndex === i}
    <div class="ach-card" class:open={isOpen}>
      <button
        class="ach-header"
        onclick={() => {
          toggle(i);
        }}
        aria-expanded={isOpen}
      >
        <div class="ach-title-row">
          <Badge
            text={achievement.tag}
            color={achievement.accent ? 'green' : 'primary'}
            class="ach-tag"
          />
          <span class="ach-title">{achievement.title}</span>
        </div>
        <div class="ach-header-right">
          <div class="ach-chevron" class:open={isOpen}>
            <ChevronDown size={18} strokeWidth={2} />
          </div>
        </div>
      </button>
      {#if isOpen || isPrintMode}
        <div class="ach-body" transition:slide={{ duration: isPrintMode ? 0 : 250 }}>
          <!-- eslint-disable-next-line svelte/no-at-html-tags -->
          <div class="ach-desc">{@html achievement.detail}</div>
        </div>
      {/if}
    </div>
  {/each}
</div>

<style>
  .achievements {
    display: flex;
    flex-direction: column;
    gap: 12px;
    margin-bottom: 56px;
  }

  .ach-card {
    border: 1px solid var(--color-bg-divider);
    border-radius: 12px;
    background: var(--color-basic-bg);
    overflow: hidden;
    transition: all 0.2s ease;
  }

  .ach-card:hover {
    border-color: var(--color-sub);
  }

  .ach-card.open {
    border-color: var(--color-primary);
    box-shadow: 0 4px 12px var(--color-shadow);
  }

  .ach-header {
    width: 100%;
    padding: 16px 20px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
    cursor: pointer;
    user-select: none;
    background: transparent;
    border: none;
    text-align: left;
  }

  .ach-title-row {
    display: flex;
    align-items: center;
    gap: 12px;
    flex: 1;
  }

  :global(.ach-tag) {
    flex-shrink: 0;
    min-width: 60px;
    text-align: center;
  }

  .ach-title {
    font-size: 1.0625rem;
    font-weight: 600;
    color: var(--color-bold);
    line-height: 1.4;
  }

  .ach-header-right {
    display: flex;
    align-items: center;
    color: var(--color-sub);
  }

  .ach-chevron {
    transition: transform 0.2s;
    flex-shrink: 0;
  }

  .ach-chevron.open {
    transform: rotate(180deg);
    color: var(--color-primary);
  }

  .ach-body {
    padding: 0 20px 20px;
  }

  .ach-desc {
    font-size: 0.9375rem;
    color: var(--color-main);
    line-height: 1.6;
    border-top: 1px solid var(--color-bg-subdivider);
    padding-top: 16px;
  }

  :global(.ach-desc strong) {
    color: var(--color-bold);
    font-weight: 700;
  }

  :global(.ach-desc code) {
    background: var(--color-code-bg);
    color: var(--color-inline-code);
    padding: 2px 5px;
    border-radius: 4px;
  }

  :global(.ach-desc img) {
    width: 100%;
    margin-top: 12px;
    border-radius: 8px;
  }

  :global(.ach-desc table) {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
    margin-top: 0.75rem;
  }

  :global(.ach-desc td),
  :global(.ach-desc th) {
    padding: 6px 8px;
    border-bottom: 1px solid var(--color-bg-divider);
    text-align: left;
  }

  @media (max-width: 640px) {
    .ach-header {
      padding: 14px 16px;
      gap: 12px;
    }

    .ach-title-row {
      flex-direction: column;
      align-items: flex-start;
      gap: 8px;
    }

    .ach-title {
      font-size: 0.9375rem;
    }

    .ach-body {
      padding: 0 16px 16px;
    }
  }
</style>

// src/components/portfolio/project-detail/ProjectAchievements.tsx
"use client";

import React, { useState } from "react";
import { ChevronDown } from "lucide-react";

import Badge from "@/components/ui/Badge";
import { sanitizeProjectHtml } from "@/lib/utils/safeHtml";

import styles from "./ProjectAchievements.module.css";

export interface Achievement {
  tag: string;
  accent?: boolean;
  title: string;
  detail: string;
}

interface Props {
  achievements: Achievement[];
}

export default function ProjectAchievements({ achievements }: Props) {
  const firstAccentIndex = achievements.findIndex((a) => a.accent);
  const [openIndex, setOpenIndex] = useState<number>(
    firstAccentIndex >= 0 ? firstAccentIndex : 0
  );

  const sanitizedAchievements = achievements.map((achievement) => ({
    ...achievement,
    detail: sanitizeProjectHtml(achievement.detail),
  }));

  const toggle = (index: number) => {
    setOpenIndex((prev) => (prev === index ? -1 : index));
  };

  return (
    <div className={styles.achievements}>
      {sanitizedAchievements.map((achievement, i) => {
        const isOpen = openIndex === i;

        return (
          <div
            key={i}
            className={`${styles["ach-card"]} ${isOpen ? styles.open : ""}`}
          >
            <button
              className={styles["ach-header"]}
              onClick={() => toggle(i)}
              aria-expanded={isOpen}
            >
              <div className={styles["ach-title-row"]}>
                <Badge
                  text={achievement.tag}
                  color={achievement.accent ? "green" : "primary"}
                  className={styles["ach-tag"]}
                />
                <span className={styles["ach-title"]}>{achievement.title}</span>
              </div>
              <div className={styles["ach-header-right"]}>
                <div
                  className={`${styles["ach-chevron"]} ${isOpen ? styles.open : ""}`}
                >
                  <ChevronDown size={18} strokeWidth={2} />
                </div>
              </div>
            </button>
            <div
              className={`${styles["ach-body-wrapper"]} ${isOpen ? styles.open : ""}`}
            >
              <div className={styles["ach-body"]}>
                <div
                  className={styles["ach-desc"]}
                  dangerouslySetInnerHTML={{ __html: achievement.detail }}
                />
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
