// src/lib/components/WorkAccordion.svelte
<script lang="ts">
  import CompanyCard from '$lib/components/CompanyCard.svelte';
  import { getLabels } from '$lib/data/labels';
  import { skillState } from '$lib/states/skills.svelte';
  import type { WorkExperienceProps } from '$lib/types/about';
  import type { Language } from '$lib/utils/language';

  interface Props {
    experiences: WorkExperienceProps[];
    locale: Language;
  }

  let { experiences, locale }: Props = $props();

  let labels = $derived(getLabels(locale));
  let isFiltered = $derived(!skillState.isEmpty);
</script>

<div class="accordion">
  {#each experiences as exp (exp.companyName)}
    <CompanyCard {exp} {isFiltered} {labels} />
  {/each}
</div>

<style>
  .accordion {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
</style>

// src/components/portfolio/home/WorkAccordion.tsx
'use client';

import type { WorkExperienceProps } from '@/lib/portfolio/homeTypes';
import { getLabels } from '@/lib/portfolio/labels';
import type { Language } from '@/lib/utils/language';

import CompanyCard from './CompanyCard';
import * as styles from './WorkAccordion.css';

interface Props {
  experiences: WorkExperienceProps[];
  locale: Language;
}

export default function WorkAccordion({ experiences, locale }: Props) {
  const labels = getLabels(locale);
  const isFiltered = false;

  return (
    <div className={styles.accordion}>
      {experiences.map((exp) => {
        return (
          <CompanyCard key={exp.companyName} exp={exp} isFiltered={isFiltered} labels={labels} />
        );
      })}
    </div>
  );
}
