// src/lib/components/ExperienceList.tsx
"use client";

import React from "react";

import ArrowLink from "@/lib/components/ArrowLink";
import Badge from "@/lib/components/Badge";
import RichText from "@/lib/components/RichText";
import SkillChip from "@/lib/components/SkillChip";
import type { Labels } from "@/lib/data/labels";
import { skillState } from "@/lib/states/skills";
import type { OtherExperienceProps } from "@/lib/types/about";
import { parseMarkdown } from "@/lib/utils/markdown";

import styles from "./ExperienceList.module.css";

interface Props {
  experiences: OtherExperienceProps[];
  labels: Labels;
  skillLimit?: number;
}

export default function ExperienceList({ experiences, labels, skillLimit }: Props) {
  const formatDate = (dateFrom?: string, dateTo?: string) => {
    if (!dateFrom) return "";
    if (dateFrom.length === 4) return dateFrom; // e.g. 2024
    const formatted = dateFrom.replace("-", ".");
    const isOngoing = !dateTo || dateTo !== dateFrom;
    return isOngoing ? `${formatted} ~` : formatted;
  };

  return (
    <div className={styles["experience-list"]}>
      {experiences.map((exp) => {
        const project = exp.project[0];
        if (!project) return null;

        const featuredSkills = project.featuredSkills ?? [];
        const remainingSkills = skillState
          .sort(project.skills ?? [])
          .filter((skill) => !featuredSkills.includes(skill));
        const sortedSkills = skillLimit
          ? [...featuredSkills, ...remainingSkills]
          : skillState.sort(project.skills ?? []);
        const visibleSkills = skillLimit
          ? sortedSkills.slice(0, skillLimit)
          : sortedSkills;
        const hiddenSkillCount = sortedSkills.length - visibleSkills.length;
        const metricCount = project.metrics
          ? Math.min(project.metrics.length, 4)
          : 0;

        return (
          <div
            key={project.title}
            className={styles["item-wrapper"]}
          >
            <div className={styles.item}>
              <div className={styles.content}>
                <div className={styles.header}>
                  <h3 className={styles.title}>{project.title}</h3>
                  {exp.titleBadge && <Badge text={exp.titleBadge} />}
                </div>
                <p className={styles.description}>
                  <RichText parts={parseMarkdown(project.description)} />
                </p>

                {project.metrics && project.metrics.length > 0 && (
                  <dl
                    className={`${styles["metric-strip"]} ${
                      metricCount === 4 ? styles["has-four-metrics"] : ""
                    }`}
                    style={{ "--metric-count": metricCount } as React.CSSProperties}
                  >
                    {project.metrics.map((metric) => (
                      <div key={metric.label} className={styles["metric-item"]}>
                        <dt>{metric.label}</dt>
                        <dd>{metric.value}</dd>
                      </div>
                    ))}
                  </dl>
                )}

                {project.detailLink && (
                  <div className={styles["link-wrapper"]}>
                    <ArrowLink
                      href={project.detailLink}
                      label={labels.viewProjectDetails}
                      reload
                    />
                  </div>
                )}

                {project.skills && project.skills.length > 0 && (
                  <div className={styles["tag-list"]}>
                    {visibleSkills.map((skill) => (
                      <SkillChip key={skill} skill={skill} />
                    ))}
                    {hiddenSkillCount > 0 && (
                      <span
                        className={styles["more-chip"]}
                        title={sortedSkills.slice(skillLimit).join(", ")}
                      >
                        +{hiddenSkillCount}
                      </span>
                    )}
                  </div>
                )}
              </div>
              <div className={styles["date-wrapper"]}>
                <span className={styles.date}>
                  {formatDate(project.dateFrom, project.dateTo)}
                </span>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

// src/lib/components/ExperienceList.svelte
<script lang="ts">
  import { flip } from 'svelte/animate';
  import { slide } from 'svelte/transition';

  import ArrowLink from '$lib/components/ArrowLink.svelte';
  import Badge from '$lib/components/Badge.svelte';
  import RichText from '$lib/components/RichText.svelte';
  import SkillChip from '$lib/components/SkillChip.svelte';
  import { getLabels } from '$lib/data/labels';
  import { skillState } from '$lib/states/skills.svelte';
  import type { OtherExperienceProps } from '$lib/types/about';
  import { getPageLocale } from '$lib/utils/locale';
  import { parseMarkdown } from '$lib/utils/markdown';

  interface Props {
    experiences: OtherExperienceProps[];
    skillLimit?: number;
  }

  let { experiences, skillLimit }: Props = $props();

  let labels = $derived(getLabels(getPageLocale()));

  const formatDate = (dateFrom?: string, dateTo?: string) => {
    if (!dateFrom) return '';
    if (dateFrom.length === 4) return dateFrom; // e.g. 2024
    const formatted = dateFrom.replace('-', '.');
    const isOngoing = !dateTo || dateTo !== dateFrom;
    return isOngoing ? formatted + ' ~' : formatted;
  };
</script>

<div class="experience-list">
  {#each experiences as exp (exp.project[0].title)}
    {@const project = exp.project[0]}
    <div class="item-wrapper" animate:flip={{ duration: 400 }} transition:slide={{ duration: 300 }}>
      <div class="item">
        <div class="content">
          <div class="header">
            <h3 class="title">{project.title}</h3>
            {#if exp.titleBadge}
              <Badge text={exp.titleBadge} />
            {/if}
          </div>
          <p class="description">
            <RichText parts={parseMarkdown(project.description)} />
          </p>

          {#if project.metrics && project.metrics.length > 0}
            <dl class="metric-strip" style:--metric-count={Math.min(project.metrics.length, 4)}>
              {#each project.metrics as metric (metric.label)}
                <div class="metric-item">
                  <dt>{metric.label}</dt>
                  <dd>{metric.value}</dd>
                </div>
              {/each}
            </dl>
          {/if}

          {#if project.detailLink}
            <div class="link-wrapper">
              <ArrowLink href={project.detailLink} label={labels.viewProjectDetails} reload />
            </div>
          {/if}

          {#if project.skills}
            {@const featuredSkills = project.featuredSkills ?? []}
            {@const remainingSkills = skillState
              .sort(project.skills)
              .filter((skill) => !featuredSkills.includes(skill))}
            {@const sortedSkills = skillLimit
              ? [...featuredSkills, ...remainingSkills]
              : skillState.sort(project.skills)}
            {@const visibleSkills = skillLimit ? sortedSkills.slice(0, skillLimit) : sortedSkills}
            {@const hiddenSkillCount = sortedSkills.length - visibleSkills.length}
            <div class="tag-list">
              {#each visibleSkills as skill (skill)}
                <SkillChip {skill} />
              {/each}
              {#if hiddenSkillCount > 0}
                <span class="more-chip" title={sortedSkills.slice(skillLimit).join(', ')}>
                  +{hiddenSkillCount}
                </span>
              {/if}
            </div>
          {/if}
        </div>
        <div class="date-wrapper">
          <span class="date">{formatDate(project.dateFrom, project.dateTo)}</span>
        </div>
      </div>
    </div>
  {/each}
</div>

<style>
  .experience-list {
    display: flex;
    flex-direction: column;
    gap: var(--space-md);
    margin-top: var(--space-md);
  }

  .item-wrapper {
    display: flex;
    flex-direction: column;
  }

  .item {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: var(--space-md);
    min-width: 0;
  }

  .content {
    flex: 1;
    min-width: 0;
  }

  .header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .title {
    font-size: var(--font-h3);
    font-weight: 700;
    margin: 0;
    color: var(--color-bold);
    overflow-wrap: anywhere;
  }

  .link-wrapper {
    margin-bottom: 0.75rem;
  }

  .description {
    font-size: 0.9375rem;
    color: var(--color-main);
    margin: 0 0 0.5rem 0;
    line-height: 1.5;
    overflow-wrap: anywhere;
  }

  .metric-strip {
    border: 1px solid var(--color-bg-divider);
    border-radius: 10px;
    display: grid;
    gap: 0;
    grid-template-columns: repeat(var(--metric-count), minmax(0, 1fr));
    margin: 0 0 0.75rem;
    padding: 0.25rem;
  }

  .metric-item {
    align-items: flex-start;
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    padding: 0.65rem;
  }

  .metric-item dd {
    color: var(--color-primary);
    font-size: 0.95rem;
    font-weight: 800;
    line-height: 1;
    margin: 0;
    white-space: nowrap;
  }

  .metric-item dt {
    color: var(--color-sub);
    font-size: 0.75rem;
    line-height: 1.2;
  }

  .tag-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.375rem;
    min-width: 0;
  }

  .more-chip {
    align-items: center;
    border: 1px dashed var(--color-bg-divider);
    border-radius: 6px;
    color: var(--color-sub);
    display: inline-flex;
    font-size: 0.8125rem;
    font-weight: 600;
    line-height: 1;
    padding: 0.35rem 0.6rem;
    white-space: nowrap;
  }

  .date-wrapper {
    flex-shrink: 0;
    text-align: right;
  }

  .date {
    font-size: 0.875rem;
    color: var(--color-placeholder);
    white-space: nowrap;
  }

  @media (max-width: 768px) {
    .item {
      flex-direction: column;
      gap: 0.5rem;
    }
    .date-wrapper {
      order: -1;
      text-align: left;
    }

    .metric-item {
      padding: 0.55rem;
    }
  }
</style>
