// src/lib/components/Footer.svelte
<script lang="ts">
  import ShareButton from '$lib/components/ShareButton.svelte';
  import { getLabels } from '$lib/data/labels';
  import { getPageLocale } from '$lib/utils/locale';

  let labels = $derived(getLabels(getPageLocale()));
</script>

<footer class="wrapper">
  <ShareButton variant="text" shareLabel={labels.shareFooter} copiedLabel={labels.linkCopied} />
</footer>

<style>
  .wrapper {
    align-items: center;
    border-top: 1px solid var(--color-bg-divider);
    display: flex;
    justify-content: center;
    padding: var(--space-sm);
  }

  @media print {
    .wrapper {
      display: none !important;
    }
  }
</style>

// src/lib/components/Footer.tsx
"use client";

import React from "react";

import { useLocale } from "@/lib/contexts/LocaleContext";

import styles from "./Footer.module.css";
import ShareButton from "./ShareButton";

export default function Footer() {
  const { labels } = useLocale();

  return (
    <footer className={styles.wrapper}>
      <ShareButton
        variant="text"
        shareLabel={labels.shareFooter}
        copiedLabel={labels.linkCopied}
      />
    </footer>
  );
}
