// src/components/ui/Period.tsx
import React from "react";

interface Props {
  dateFrom: string;
  dateTo?: string;
}

export default function Period({ dateFrom, dateTo }: Props) {
  const timeFormatter = (time?: string) => {
    if (!time) return "";
    const [year, month = ""] = time.split("-");
    return `${year}. ${month}`;
  };

  const showTilde = dateFrom.includes("-") && (!dateTo || dateTo !== dateFrom);
  const showDateTo = dateTo && dateTo !== dateFrom;

  return (
    <span>
      <time dateTime={dateFrom}>{timeFormatter(dateFrom)}</time>
      {showTilde && " ~ "}
      {showDateTo && <time dateTime={dateTo}>{timeFormatter(dateTo)}</time>}
    </span>
  );
}

// src/lib/components/Period.svelte
<script lang="ts">
  interface Props {
    dateFrom: string;
    dateTo?: string;
  }

  let { dateFrom, dateTo }: Props = $props();

  const timeFormatter = (time?: string) => {
    if (!time) return '';
    const [year, month = ''] = time.split('-');
    return `${year}. ${month}`;
  };
</script>

<span
  ><time datetime={dateFrom}>{timeFormatter(dateFrom)}</time>{#if dateFrom.includes('-') && (!dateTo || dateTo !== dateFrom)}
    ~
  {/if}{#if dateTo && dateTo !== dateFrom}<time datetime={dateTo}>{timeFormatter(dateTo)}</time>{/if}</span
>
