// src/lib/components/ProjectItem.tsx
"use client";

import React, { useMemo } from "react";
import { ChevronDown } from "lucide-react";

import type { Labels } from "@/lib/data/labels";
import { useAccordionState } from "@/lib/states/accordion";
import { useSkillState } from "@/lib/states/skills";
import type { ProjectItem as ProjectItemType } from "@/lib/types/about";
import { parseMarkdown } from "@/lib/utils/markdown";

import ArrowLink from "./ArrowLink";
import Period from "./Period";
import ProjectItemStyles from "./ProjectItem.module.css";
import RichText from "./RichText";
import SkillChip from "./SkillChip";

interface Props {
  companyName: string;
  editTrigger?: React.ReactNode;
  editor?: React.ReactNode;
  isEditing?: boolean;
  isFiltered: boolean;
  labels: Labels;
  project: ProjectItemType;
}

export default function ProjectItem({
  companyName,
  editTrigger,
  editor,
  isEditing = false,
  isFiltered,
  labels,
  project,
}: Props) {
  const { isProjectOpen, toggleProject } = useAccordionState();
  const { sort } = useSkillState();

  const isOpen = isProjectOpen(companyName, project.title) || isFiltered;

  const sortedSkills = useMemo(() => {
    return project.skills ? sort(project.skills) : [];
  }, [project.skills, sort]);

  const mainSkillsLabel = useMemo(() => {
    return sortedSkills.slice(0, 2).join(", ");
  }, [sortedSkills]);

  function parseDetailLine(line: string) {
    const match = line.match(/^\*\*\[(.*?)\]\*\*(.*)$/);
    if (match) {
      return { label: match[1], content: match[2].trim() };
    }
    return { label: null, content: line };
  }

  const metricCount = project.metrics ? Math.min(project.metrics.length, 4) : 0;

  const handleToggle = () => {
    if (!isFiltered) toggleProject(companyName, project.title);
  };

  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (!isFiltered && (event.key === "Enter" || event.key === " ")) {
      event.preventDefault();
      toggleProject(companyName, project.title);
    }
  };

  if (isEditing) {
    return (
      <div className={`${ProjectItemStyles["project-item"]} ${ProjectItemStyles["is-open"]}`}>
        <div className={ProjectItemStyles["project-editor-slot"]}>{editor}</div>
      </div>
    );
  }

  return (
    <div className={`${ProjectItemStyles["project-item"]} ${isOpen ? ProjectItemStyles["is-open"] : ""}`}>
      <div
        className={ProjectItemStyles["project-header"]}
        onClick={handleToggle}
        onKeyDown={handleKeyDown}
        aria-expanded={isOpen}
        role="button"
        tabIndex={0}
      >
        <div className={ProjectItemStyles["project-title-area"]}>
          <div className={ProjectItemStyles["project-title-row"]}>
            <span className={ProjectItemStyles["project-title"]}>{project.title}</span>
            {editTrigger && (
              <span
                className={ProjectItemStyles["project-edit-action"]}
                onClick={(event) => event.stopPropagation()}
                onKeyDown={(event) => event.stopPropagation()}
              >
                {editTrigger}
              </span>
            )}
            <span className={`${ProjectItemStyles["project-period"]} ${ProjectItemStyles["mobile-only"]}`}>
              <Period dateFrom={project.dateFrom} dateTo={project.dateTo} />
            </span>
          </div>
          <div className={ProjectItemStyles["project-desc-line"]}>
            <span className={ProjectItemStyles["project-description-short"]}>{project.description}</span>
            {project.skills && project.skills.length > 0 && (
              <>
                <span className={ProjectItemStyles["desc-separator"]}>·</span>
                <span className={ProjectItemStyles["main-skills"]}>{mainSkillsLabel}</span>
              </>
            )}
          </div>
        </div>
        <div className={ProjectItemStyles["project-header-right"]}>
          <span className={`${ProjectItemStyles["project-period"]} ${ProjectItemStyles["pc-only"]}`}>
            <Period dateFrom={project.dateFrom} dateTo={project.dateTo} />
          </span>
          <ChevronDown
            size={20}
            strokeWidth={2}
            className={`${ProjectItemStyles["project-chevron"]} ${isOpen ? ProjectItemStyles.open : ""}`}
          />
        </div>
      </div>

      {isOpen && (
        <div className={ProjectItemStyles["project-content"]}>
          {project.metrics && project.metrics.length > 0 && (
            <div
              className={`${ProjectItemStyles["project-metrics"]} ${
                metricCount === 4 ? ProjectItemStyles["has-four-metrics"] : ""
              }`}
              style={{ "--metric-count": metricCount } as React.CSSProperties}
            >
              {project.metrics.map((metric) => (
                <div className={ProjectItemStyles["metric-item"]} key={metric.label}>
                  <span className={ProjectItemStyles["metric-value"]}>{metric.value}</span>
                  <span className={ProjectItemStyles["metric-label"]}>{metric.label}</span>
                </div>
              ))}
            </div>
          )}

          {project.detail.length > 0 && (
            <div className={ProjectItemStyles["detail-grid"]}>
              {project.detail.map((line) => {
                const parsed = parseDetailLine(line);
                return (
                  <div className={ProjectItemStyles["detail-row"]} key={line}>
                    {parsed.label && (
                      <div className={ProjectItemStyles["detail-label"]}>
                        <span className={ProjectItemStyles["label-pill"]}>{parsed.label}</span>
                      </div>
                    )}
                    <div className={ProjectItemStyles["detail-text"]}>
                      <RichText parts={parseMarkdown(parsed.content)} />
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {project.detailLink && (
            <div className={ProjectItemStyles["project-links"]}>
              <ArrowLink href={project.detailLink} label={labels.viewProjectDetails} />
            </div>
          )}

          {project.skills && project.skills.length > 0 && (
            <div className={ProjectItemStyles["skill-tags"]}>
              {sortedSkills.map((skill) => (
                <SkillChip key={skill} skill={skill} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// src/lib/components/ProjectItem.svelte
<script lang="ts">
  import { slide } from 'svelte/transition';
  import { ChevronDown } from 'lucide-svelte';

  import ArrowLink from '$lib/components/ArrowLink.svelte';
  import Period from '$lib/components/Period.svelte';
  import RichText from '$lib/components/RichText.svelte';
  import SkillChip from '$lib/components/SkillChip.svelte';
  import type { Labels } from '$lib/data/labels';
  import { accordionState } from '$lib/states/accordion.svelte';
  import { skillState } from '$lib/states/skills.svelte';
  import type { ProjectItem as ProjectItemType } from '$lib/types/about';
  import { parseMarkdown } from '$lib/utils/markdown';

  interface Props {
    companyName: string;
    isFiltered: boolean;
    labels: Labels;
    project: ProjectItemType;
  }

  let { companyName, isFiltered, labels, project }: Props = $props();

  let isOpen = $derived(accordionState.isProjectOpen(companyName, project.title) || isFiltered);

  function parseDetailLine(line: string) {
    const match = line.match(/^\*\*\[(.*?)\]\*\*(.*)$/);
    if (match) {
      return { label: match[1], content: match[2].trim() };
    }
    return { label: null, content: line };
  }
</script>

<div class={['project-item', isOpen && 'is-open']} transition:slide={{ duration: 200 }}>
  <!-- Project row header -->
  <button
    class="project-header"
    onclick={() => {
      if (!isFiltered) accordionState.toggleProject(companyName, project.title);
    }}
    aria-expanded={isOpen}
  >
    <div class="project-title-area">
      <div class="project-title-row">
        <span class="project-title">{project.title}</span>
        <span class="project-period mobile-only">
          <Period dateFrom={project.dateFrom} dateTo={project.dateTo} />
        </span>
      </div>
      <div class="project-desc-line">
        <span class="project-description-short">{project.description}</span>
        {#if project.skills && project.skills.length > 0}
          <span class="desc-separator">·</span>
          <span class="main-skills">{skillState.sort(project.skills).slice(0, 2).join(', ')}</span>
        {/if}
      </div>
    </div>
    <div class="project-header-right">
      <span class="project-period pc-only">
        <Period dateFrom={project.dateFrom} dateTo={project.dateTo} />
      </span>
      <ChevronDown size={20} strokeWidth={2} class={`project-chevron ${isOpen ? 'open' : ''}`} />
    </div>
  </button>

  <!-- Level 2 expand: project details -->
  {#if isOpen}
    <div class="project-content" transition:slide={{ duration: 200 }}>
      {#if project.metrics && project.metrics.length > 0}
        {@const metricCount = Math.min(project.metrics.length, 4)}
        <div
          class="project-metrics"
          class:has-four-metrics={metricCount === 4}
          style:--metric-count={metricCount}
        >
          {#each project.metrics as metric (metric.label)}
            <div class="metric-item">
              <span class="metric-value">{metric.value}</span>
              <span class="metric-label">{metric.label}</span>
            </div>
          {/each}
        </div>
      {/if}

      {#if project.detail.length > 0}
        <div class="detail-grid">
          {#each project.detail as line (line)}
            {@const parsed = parseDetailLine(line)}
            <div class="detail-row">
              {#if parsed.label}
                <div class="detail-label">
                  <span class="label-pill">{parsed.label}</span>
                </div>
              {/if}
              <div class="detail-text">
                <RichText parts={parseMarkdown(parsed.content)} />
              </div>
            </div>
          {/each}
        </div>
      {/if}

      {#if project.detailLink}
        <div class="project-links">
          <ArrowLink href={project.detailLink} label={labels.viewProjectDetails} />
        </div>
      {/if}

      {#if project.skills && project.skills.length > 0}
        <div class="skill-tags">
          {#each skillState.sort(project.skills) as skill (skill)}
            <SkillChip {skill} />
          {/each}
        </div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .project-item {
    border-bottom: 1px solid var(--color-bg-divider);
    min-width: 0;
    transition: background-color 0.15s;
  }

  .project-item:last-child {
    border-bottom: none;
  }

  .project-header {
    align-items: center;
    background: transparent;
    border: none;
    cursor: pointer;
    display: flex;
    gap: 1rem;
    justify-content: space-between;
    padding: 1rem;
    text-align: left;
    width: 100%;
    font-family: inherit;
    min-width: 0;
  }

  .project-title-area {
    display: flex;
    flex-direction: column;
    flex: 1;
    gap: 0.25rem;
    min-width: 0;
  }

  .project-title-row {
    align-items: center;
    display: flex;
    gap: 0.5rem;
    justify-content: space-between;
  }

  .project-title {
    color: var(--color-bold);
    font-size: 1.125rem;
    font-weight: 600;
    margin: 0;
    overflow-wrap: anywhere;
  }

  .project-desc-line {
    align-items: center;
    color: var(--color-sub);
    display: flex;
    font-size: 0.9375rem;
    gap: 0.4rem;
    flex-wrap: wrap;
    min-width: 0;
    overflow-wrap: anywhere;
  }

  .desc-separator {
    opacity: 0.5;
  }

  .project-header-right {
    align-items: center;
    display: flex;
    gap: 1rem;
  }

  .project-period {
    color: var(--color-sub);
    font-size: 0.875rem;
    white-space: nowrap;
  }

  :global(.project-chevron) {
    transition: transform 0.2s;
    flex-shrink: 0;
    color: var(--color-sub);
  }

  :global(.project-chevron.open),
  .project-header:hover :global(.project-chevron) {
    transform: rotate(180deg);
    color: var(--color-primary);
  }

  .project-content {
    background: transparent;
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
    min-width: 0;
    padding: 0 1rem 1.25rem 1rem;
  }

  .project-metrics {
    border: 1px solid var(--color-bg-divider);
    border-radius: 10px;
    display: grid;
    grid-template-columns: repeat(var(--metric-count), minmax(0, 1fr));
    gap: 0;
    margin-top: 0.5rem;
    padding: 0.25rem;
  }

  .metric-item {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    padding: 0.65rem;
  }

  .metric-value {
    color: var(--color-primary);
    font-size: 1.125rem;
    font-weight: 700;
  }

  .metric-label {
    color: var(--color-sub);
    font-size: 0.75rem;
  }

  @media (max-width: 420px) {
    .project-metrics.has-four-metrics {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
  }

  .detail-grid {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .detail-row {
    display: flex;
    flex-direction: column;
    gap: 0.4rem;
  }

  .detail-label {
    width: fit-content;
  }

  .label-pill {
    background: var(--color-bg-subdivider);
    border-radius: 6px;
    color: var(--color-sub);
    font-size: 0.8125rem;
    font-weight: 600;
    padding: 0.3rem 0.6rem;
    display: inline-block;
    line-height: 1.3;
    white-space: nowrap;
  }

  .detail-text {
    color: var(--color-main);
    font-size: 1rem;
    line-height: 1.6;
    flex: 1;
    min-width: 0;
    overflow-wrap: anywhere;
  }

  .skill-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }

  .project-links {
    display: flex;
    gap: 1rem;
  }

  .pc-only {
    display: block;
  }

  .mobile-only {
    display: none;
  }

  @media (max-width: 576px) {
    .pc-only {
      display: none;
    }
    .mobile-only {
      display: block;
    }

    .project-title-row {
      align-items: flex-start;
      flex-direction: column;
      gap: 0.2rem;
    }

    .project-header {
      padding: 0.875rem;
    }

    .metric-item {
      padding: 0.55rem;
    }
  }
</style>
