// src/lib/components/ReadingProgress.tsx
"use client";

import React, { useEffect,useState } from "react";

import { getPageScrollElement, getPageScrollHeight, getPageScrollY } from "@/lib/hooks/useScrollSpy";

import styles from "./ReadingProgress.module.css";

export default function ReadingProgress() {
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    if (typeof window === "undefined") return;

    function update() {
      const scrollEl = getPageScrollElement();
      // clientHeight might not be available on empty or SSR elements immediately
      const clientHeight = scrollEl.clientHeight || window.innerHeight;
      const maxScrollY = getPageScrollHeight() - clientHeight;
      setProgress(maxScrollY > 0 ? (getPageScrollY() / maxScrollY) * 100 : 0);
    }

    const scrollElement = getPageScrollElement();

    // Check if element has addEventListener method
    if (scrollElement && typeof scrollElement.addEventListener === "function") {
      scrollElement.addEventListener("scroll", update, { passive: true });
    }
    window.addEventListener("scroll", update, { passive: true });
    update();

    return () => {
      if (scrollElement && typeof scrollElement.removeEventListener === "function") {
        scrollElement.removeEventListener("scroll", update);
      }
      window.removeEventListener("scroll", update);
    };
  }, []);

  return (
    <div className={styles["progress-bar"]} style={{ width: `${progress}%` }} />
  );
}

// src/lib/components/ReadingProgress.svelte
<script lang="ts">
  import {
    getPageScrollElement,
    getPageScrollHeight,
    getPageScrollY,
  } from '$lib/states/scrollSpy.svelte';

  let progress = $state(0);

  $effect(() => {
    function update() {
      const maxScrollY = getPageScrollHeight() - getPageScrollElement().clientHeight;
      progress = maxScrollY > 0 ? (getPageScrollY() / maxScrollY) * 100 : 0;
    }

    const scrollElement = getPageScrollElement();

    scrollElement.addEventListener('scroll', update, { passive: true });
    window.addEventListener('scroll', update, { passive: true });
    update();

    return () => {
      scrollElement.removeEventListener('scroll', update);
      window.removeEventListener('scroll', update);
    };
  });
</script>

<div class="progress-bar" style="width: {progress}%"></div>

<style>
  .progress-bar {
    background: var(--color-primary);
    height: 2px;
    left: 0;
    position: fixed;
    top: 0;
    transition: width 0.1s linear;
    z-index: 200;
  }

  @media print {
    .progress-bar {
      display: none !important;
    }
  }
</style>
