// src/lib/components/RichText.svelte
<script lang="ts">
  import type { TextPart } from '$lib/utils/markdown';

  interface Props {
    parts: TextPart[];
  }

  let { parts }: Props = $props();
</script>

{#each parts as part, i (i)}
  {#if part.type === 'bold'}
    <strong>{part.text}</strong>
  {:else if part.type === 'code'}
    <code>{part.text}</code>
  {:else}
    {part.text}
  {/if}
{/each}

// src/lib/components/RichText.tsx
import React from "react";

import type { TextPart } from "@/lib/utils/markdown";

interface Props {
  parts: TextPart[];
}

export default function RichText({ parts }: Props) {
  return (
    <>
      {parts.map((part, i) => {
        if (part.type === "bold") {
          return <strong key={i}>{part.text}</strong>;
        }
        if (part.type === "code") {
          return <code key={i}>{part.text}</code>;
        }
        return <React.Fragment key={i}>{part.text}</React.Fragment>;
      })}
    </>
  );
}
