// src/lib/components/SkillChip.tsx
"use client";

import React from "react";

import { useSkillState } from "@/lib/states/skills";

import styles from "./SkillChip.module.css";

interface Props {
  skill: string;
  readonly?: boolean;
}

export default function SkillChip({ skill, readonly = false }: Props) {
  const { has, toggle, getCategory } = useSkillState();

  const category = getCategory(skill);
  const isActive = !readonly && has(skill);

  const inlineStyles = {
    "--cat-color": `var(--color-cat-${category})`,
    "--cat-text-hover": category === "ai_workflow"
      ? "var(--color-cat-ai_workflow-text, white)"
      : "white",
  } as React.CSSProperties;

  const combinedClass = [
    styles["skill-chip"],
    isActive && styles.active,
    readonly && styles.readonly,
  ]
    .filter(Boolean)
    .join(" ");

  const handleClick = (e: React.MouseEvent | React.KeyboardEvent) => {
    if (readonly) return;
    if ("key" in e && e.key !== "Enter" && e.key !== " ") return;
    toggle(skill);
  };

  return (
    <button
      className={combinedClass}
      style={inlineStyles}
      onClick={handleClick}
      onKeyDown={handleClick}
      aria-pressed={!readonly ? isActive : undefined}
    >
      {skill}
    </button>
  );
}

// src/lib/components/SkillChip.svelte
<script lang="ts">
  import { skillState } from '$lib/states/skills.svelte';

  interface Props {
    skill: string;
    readonly?: boolean;
  }
  let { skill, readonly = false }: Props = $props();

  let category = $derived(skillState.getCategory(skill));

  function handleClick(e: MouseEvent | KeyboardEvent) {
    if (readonly) return;
    if (e instanceof KeyboardEvent && e.key !== 'Enter' && e.key !== ' ') return;
    skillState.toggle(skill);
  }
</script>

<button
  class={['skill-chip', !readonly && skillState.has(skill) && 'active', readonly && 'readonly']}
  style:--cat-color="var(--color-cat-{category})"
  style:--cat-text-hover={category === 'ai_workflow'
    ? 'var(--color-cat-ai_workflow-text, white)'
    : 'white'}
  onclick={handleClick}
  onkeydown={handleClick}
  aria-pressed={!readonly && skillState.has(skill)}
>
  {skill}
</button>

<style>
  .skill-chip {
    --cat-color: var(--color-primary);
    --cat-text-hover: white;

    appearance: none;
    background: transparent;
    border: 1px solid color-mix(in srgb, var(--cat-color) 40%, var(--color-bg-divider));
    border-radius: 6px;
    color: color-mix(in srgb, var(--cat-color), black 35%);
    :global(html.dark) & {
      color: color-mix(in srgb, var(--cat-color), white 25%);
    }
    font-size: 0.875rem;
    padding: 0.35rem 0.65rem;
    font-weight: 500;
    line-height: 1;
    white-space: nowrap;
    display: inline-block;
    transition: all 0.15s ease;
    cursor: pointer;
    font-family: inherit;
    text-align: center;
  }

  .skill-chip:not(.readonly):hover {
    color: var(--cat-text-hover);
    background: var(--cat-color);
    border-color: var(--cat-color);
  }

  .skill-chip.active {
    background: var(--cat-color);
    border-color: var(--cat-color);
    color: var(--cat-text-hover);
    font-weight: 700;
    box-shadow: 0 2px 6px color-mix(in srgb, var(--cat-color) 30%, transparent);
  }
</style>
