// src/lib/components/WorkAccordion.svelte
<script lang="ts">
  import CompanyCard from '$lib/components/CompanyCard.svelte';
  import { getLabels } from '$lib/data/labels';
  import { skillState } from '$lib/states/skills.svelte';
  import type { WorkExperienceProps } from '$lib/types/about';
  import type { Language } from '$lib/utils/language';

  interface Props {
    experiences: WorkExperienceProps[];
    locale: Language;
  }

  let { experiences, locale }: Props = $props();

  let labels = $derived(getLabels(locale));
  let isFiltered = $derived(!skillState.isEmpty);
</script>

<div class="accordion">
  {#each experiences as exp (exp.companyName)}
    <CompanyCard {exp} {isFiltered} {labels} />
  {/each}
</div>

<style>
  .accordion {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }
</style>

// src/lib/components/WorkAccordion.tsx
'use client';

import React from 'react';

import { getLabels } from '@/lib/data/labels';
import { useSkillState } from '@/lib/states/skills';
import type { WorkExperienceProps } from '@/lib/types/about';
import type { Language } from '@/lib/utils/language';

import CompanyCard from './CompanyCard';
import styles from './WorkAccordion.module.css';

interface Props {
  experiences: WorkExperienceProps[];
  locale: Language;
}

export default function WorkAccordion({ experiences, locale }: Props) {
  const labels = getLabels(locale);
  const { isEmpty } = useSkillState();
  const isFiltered = !isEmpty;

  return (
    <div className={styles.accordion}>
      {experiences.map((exp) => {
        return (
          <CompanyCard
            key={exp.companyName}
            exp={exp}
            isFiltered={isFiltered}
            labels={labels}
          />
        );
      })}
    </div>
  );
}
