// src/lib/components/ArrowLink.svelte
<script lang="ts">
  interface Props {
    href: string;
    label: string;
    class?: string;
    color?: string; // Optional CSS color variable, e.g. "var(--color-primary)"
    reload?: boolean;
    target?: '_blank' | '_self' | '_parent' | '_top';
  }

  let {
    href,
    label,
    class: className = '',
    color = 'var(--color-primary)',
    reload = false,
    target = '_self',
  }: Props = $props();
</script>

<a
  {href}
  {target}
  class={['arrow-link', className]}
  style:--link-color={color}
  style:--link-bg-hover={color.includes('var(--cat-color)')
    ? `color-mix(in srgb, var(--cat-color) 10%, transparent)`
    : 'var(--color-primary-transparent)'}
  data-sveltekit-reload={reload ? '' : undefined}
  rel={target === '_blank' ? 'noopener noreferrer' : undefined}
>
  {label} →
</a>

<style>
  .arrow-link {
    font-size: 0.875rem;
    font-weight: 600;
    text-decoration: none;
    color: var(--link-color);
    display: inline-flex;
    align-items: center;
    padding: 0.25rem 0.5rem;
    margin-left: -0.5rem;
    border-radius: 4px;
    transition:
      background-color 0.2s,
      transform 0.2s;
  }

  .arrow-link:hover {
    background-color: var(--link-bg-hover);
    text-decoration: underline;
    transform: translateX(2px);
  }
</style>

// src/components/ui/ArrowLink.tsx
import Link from 'next/link';
import React from 'react';

import { arrowLink, linkBgHoverVar, linkColorVar } from './ArrowLink.css';

interface Props {
  href: string;
  label: string;
  className?: string;
  color?: string;
  target?: '_blank' | '_self' | '_parent' | '_top';
  reload?: boolean;
}

const getVarName = (variable: string) => String(variable).replace(/^var\(|\)$/g, '');

export default function ArrowLink({
  href,
  label,
  className = '',
  color = 'var(--color-primary)',
  target = '_self',
  reload = false,
}: Props) {
  const linkBgHover = color.includes('var(--cat-color)')
    ? `color-mix(in srgb, var(--cat-color) 10%, transparent)`
    : 'var(--color-primary-transparent)';

  const inlineStyles = {
    [getVarName(linkColorVar)]: color,
    [getVarName(linkBgHoverVar)]: linkBgHover,
  } as React.CSSProperties;

  const rel = target === '_blank' ? 'noopener noreferrer' : undefined;
  const combinedClass = `${arrowLink} ${className}`.trim();

  // Next.js Link handles internal routing, external or reload use direct standard anchor
  const isExternal = href.startsWith('http') || target === '_blank' || reload;

  if (isExternal) {
    return (
      <a href={href} target={target} rel={rel} className={combinedClass} style={inlineStyles}>
        {label} →
      </a>
    );
  }

  return (
    <Link href={href} className={combinedClass} style={inlineStyles}>
      {label} →
    </Link>
  );
}
