// src/lib/components/Badge.svelte
<script lang="ts">
  interface Props {
    text: string;
    color?: 'primary' | 'green' | 'orange' | 'sub' | 'android' | 'ios' | 'macos' | 'web';
    class?: string;
  }

  let { text, color, class: className = '' }: Props = $props();

  const resolvedColor = $derived.by(() => {
    if (color) return color;
    const t = text.toLowerCase();
    if (t === 'android') return 'android';
    if (t === 'ios') return 'ios';
    if (t === 'macos') return 'macos';
    if (t === 'web') return 'web';
    if (t === '현재' || t === 'present') return 'green';
    if (text.match(/^\d{4}$/)) return 'green'; // Years (2026, etc.)
    return 'orange'; // Fallback for company names or status
  });
</script>

<span class={['badge', resolvedColor, className].filter(Boolean).join(' ')}>
  {text}
</span>

// src/components/ui/Badge.tsx
interface Props {
  text: string;
  color?: 'primary' | 'green' | 'orange' | 'sub' | 'android' | 'ios' | 'macos' | 'web';
  className?: string;
}

export default function Badge({ text, color, className = '' }: Props) {
  const getResolvedColor = () => {
    if (color) return color;
    const t = text.toLowerCase();
    if (t === 'android') return 'android';
    if (t === 'ios') return 'ios';
    if (t === 'macos') return 'macos';
    if (t === 'web') return 'web';
    if (t === '현재' || t === 'present') return 'green';
    if (/^\d{4}$/.test(text)) return 'green';
    return 'orange';
  };

  const resolvedColor = getResolvedColor();
  const combinedClass = `badge ${resolvedColor} ${className}`.trim();

  return <span className={combinedClass}>{text}</span>;
}
